apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Sneha-Satish/banking-gitops.git
    targetRevision: main
    path: auth-service

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transaction-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Sneha-Satish/banking-gitops.git
    targetRevision: main
    path: transaction-service

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Sneha-Satish/banking-gitops.git
    targetRevision: main
    path: api-gateway

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-server
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Sneha-Satish/banking-gitops.git
    targetRevision: main
    path: config-server

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-registry
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Sneha-Satish/banking-gitops.git
    targetRevision: main
    path: service-registry

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true